version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    volumes:
      - line-liff-sample-rails:/var/lib/mysql
    ports:
      - "3307:3306"
    command: mysqld --innodb_use_native_aio=0

volumes:
  line-liff-sample-rails:
